language: scala
scala: 2.12.1
sudo: required
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8
install:
  - sudo apt-get update -qq
  - sudo apt-get install qemu-system qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
  - sudo mv $TRAVIS_BUILD_DIR/conf/libvirtd.conf /etc/libvirt/libvirtd.conf
  - sudo service libvirt-bin stop
script:
 - sbt -jvm-opts travis/jvmopts.compile compile
 - sbt -jvm-opts travis/jvmopts.test test
 - sbt clean coverage test coverageReport

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/repository

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - sbt coveralls
